#!/bin/sh
#
#-------------------------------------------------#
# Contributor: Joe & Pranshu                      #
# Updated on:  16 March 2018                      #
#-------------------------------------------------#
# Topic:       Rotating AMI within a VAWT         #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#

#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
#python ./time.py

##  MESHING ##
#------------------------------------------------------------------------------	
	echo "BlockMesh"
	cp -r dynamicCode.orig dynamicCode	
	blockMesh >> logMeshing
	#python ./time.py
#------------------------------------------------------------------------------
	echo "surfaceFeatureExtract"
	#surfaceFeatureExtract >> logMeshing
	#python ./time.py
#------------------------------------------------------------------------------
	echo "snappyHexMesh"
	snappyHexMesh -overwrite >> logMeshing
	#python ./time.py
#------------------------------------------------------------------------------
	echo "extrudeMesh"
	extrudeMesh >> logMeshing
	#python ./time.py
#------------------------------------------------------------------------------
	echo "createPatch"	
	createPatch -overwrite  >> logMeshing
	rm -rf 0 constant/polyMesh/sets
	#python ./time.py
#------------------------------------------------------------------------------
	#changeDictionary  >> logMeshing
	cp -r 0.orig 0

##  SIMULATION ##
#------------------------------------------------------------------------------
	echo "pimpleDyMFoam"
	pimpleDyMFoam >> logSimulation
	#python ./time.py
	echo "Postprocessing"
	cd PythonCodes
	#python ./.py
	cd ..

#------------------------------------------------------------------------------
##  OVER  ##
#------------------------------------------------------------------------------
